# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/mainForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FileRename(object):
    def setupUi(self, FileRename):
        FileRename.setObjectName("FileRename")
        FileRename.resize(602, 379)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(FileRename)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.listWidget = QtWidgets.QListWidget(FileRename)
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout_2.addWidget(self.listWidget)
        self.listWidget_preview = QtWidgets.QListWidget(FileRename)
        self.listWidget_preview.setObjectName("listWidget_preview")
        self.horizontalLayout_2.addWidget(self.listWidget_preview)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.labelFileName = QtWidgets.QLabel(FileRename)
        self.labelFileName.setObjectName("labelFileName")
        self.horizontalLayout_4.addWidget(self.labelFileName)
        self.lineEdit_FileName = QtWidgets.QLineEdit(FileRename)
        self.lineEdit_FileName.setText("")
        self.lineEdit_FileName.setObjectName("lineEdit_FileName")
        self.horizontalLayout_4.addWidget(self.lineEdit_FileName)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.refresh_btn = QtWidgets.QPushButton(FileRename)
        self.refresh_btn.setObjectName("refresh_btn")
        self.horizontalLayout.addWidget(self.refresh_btn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.select_btn = QtWidgets.QPushButton(FileRename)
        self.select_btn.setObjectName("select_btn")
        self.horizontalLayout.addWidget(self.select_btn)
        self.rename_btn = QtWidgets.QPushButton(FileRename)
        self.rename_btn.setObjectName("rename_btn")
        self.horizontalLayout.addWidget(self.rename_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(FileRename)
        QtCore.QMetaObject.connectSlotsByName(FileRename)

    def retranslateUi(self, FileRename):
        _translate = QtCore.QCoreApplication.translate
        FileRename.setWindowTitle(_translate("FileRename", "Form"))
        self.labelFileName.setText(_translate("FileRename", "Dateiname:"))
        self.lineEdit_FileName.setPlaceholderText(_translate("FileRename", "Dienstabend"))
        self.refresh_btn.setText(_translate("FileRename", "Aktualisieren"))
        self.select_btn.setText(_translate("FileRename", "Auswahl"))
        self.rename_btn.setText(_translate("FileRename", "Umbenennen"))
